### ISSUE TITLE
백엔드 최우진 배포 과제 제출입니다

### ISSUE THREAD

**Issue by wxxwls** [likelion-Inha-12/wxxwls#14]
![df](https://github.com/likelion-Inha-12/wxxwls/assets/131441769/db5b9b04-d8ca-4a06-83d8-5393a7ed8b0f)
![스크린샷 2024-05-18 211404](https://github.com/likelion-Inha-12/wxxwls/assets/131441769/4bb5a805-6118-4e50-9704-1589c91f237e)
수정했습니다!!

**Comment by juwon0403** [comment]
배포 과정 초반에 에러가 많이 떠서 따라오기 힘드셨을텐데 무사히 완주해주셔서 감사합니다,,
정말 수고 많으셨어요!!!!
